name: Docker Build and Push

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
        description: Whether to push the built images to Docker Hub
      docker_org_name:
        required: true
        type: string
      base_commit:
        required: true
        type: string
      head_commit:
        required: true
        type: string
    secrets:
      docker_username:
        required: false
      docker_password:
        required: false

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      run_docker_jobs: ${{ steps.set-matrix.outputs.run_docker_jobs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Generate Matrix Action
        id: set-matrix
        uses: submitty/action-docker-matrix@v24.06.00
        with:
          docker-username: ${{ inputs.docker_org_name }}
          base-commit: ${{ inputs.base_commit }}
          head-commit: ${{ inputs.head_commit }}
  docker:
    needs:
      - generate-matrix
    if: needs.generate-matrix.outputs.run_docker_jobs == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Hub login
        uses: docker/login-action@releases/v1
        if: ${{ inputs.push }}
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: ${{ inputs.push }}
          tags: ${{ matrix.tags }}
          platforms: linux/amd64,linux/arm64
