name: Docker Build and Push

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
        description: Whether to push the built images to Docker Hub
      docker_username:
        required: true
        type: string
      base_commit:
        required: true
        type: string
      head_commit:
        required: true
        type: string
    secrets:
      docker_password:
        required: false

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      run_docker_jobs: ${{ steps.set-matrix.outputs.run_docker_jobs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Generate Matrix Action
        id: set-matrix
        uses: submitty/action-docker-matrix@main
        with:
          docker-username: ${{ inputs.docker_username }}
          base-commit: ${{ inputs.base_commit }}
          head-commit: ${{ inputs.head_commit }}
      # - name: Set Matrix
      #   id: set-matrix
      #   run: |
      #     echo "matrix=$(python3 bin/generate_matrix.py ${{ inputs.docker_username }} ${{ github.event.before }} ${{ github.event.after }})" >> $GITHUB_OUTPUT
      # - name: List Matrix
      #   run: |
      #     echo ${{ steps.set-matrix.outputs.matrix }}
      # - name: Set Run Condition
      #   id: set-run-docker-jobs
      #   run: |
      #     num_to_build=$(echo '${{ steps.set-matrix.outputs.matrix }}' | jq '.include | length')
      #     if [[ "$num_to_build" -eq 0 ]]; then
      #       echo "run_docker_jobs=false" >> $GITHUB_OUTPUT
      #     else
      #       echo "run_docker_jobs=true" >> $GITHUB_OUTPUT
      #     fi
  docker:
    needs:
      - generate-matrix
    if: needs.generate-matrix.outputs.run_docker_jobs == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Hub login
        uses: docker/login-action@releases/v1
        if: ${{ inputs.push }}
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: ${{ inputs.push }}
          tags: ${{ matrix.tags }}
          platforms: linux/amd64,linux/arm64
